name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: scrapezoid-docs:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build with Jekyll in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -e JEKYLL_ENV=production \
          scrapezoid-docs:latest \
          bundle exec jekyll build
